records = [
    {
        "reference": "MC-2026-1045",
        "equipment": "EQ-2045",
        "technician": "Lerato Mokoena",
        "email": "lerato.mokoena@metrocare.co.za",
        "score": 87,
    },
    {
        "reference": "MC-2026-1046",
        "equipment": "EQ-3182",
        "technician": "Thabo Nkosi",
        "email": "thabo.nkosi@metrocare.co.za",
        "score": 92,
    },
    {
        "reference": "MC-2026-1047",
        "equipment": "EQ-4521",
        "technician": "Naledi Dlamini",
        "email": "naledi.dlamini@metrocare.co.za",
        "score": 78,
    },
    {
        "reference": "MC-2026-1048",
        "equipment": "EQ-6734",
        "technician": "Sipho Naidoo",
        "email": "sipho.naidoo@metrocare.co.za",
        "score": 95,
    },
    {
        "reference": "MC-2026-1049",
        "equipment": "EQ-8210",
        "technician": "Ayesha Patel",
        "email": "ayesha.patel@metrocare.co.za",
        "score": 84,
    },
    # Invalid: incorrect reference
    {
        "reference": "INVALID-1050",
        "equipment": "EQ-9055",
        "technician": "James Molefe",
        "email": "james.molefe@metrocare.co.za",
        "score": 73,
    },
    {
        "reference": "MC-2026-1051",
        "equipment": "EQ-1122",
        "technician": "Zanele Khumalo",
        "email": "zanele.khumalo@metrocare.co.za",
        "score": 81,
    },
    {
        "reference": "MC-2026-1052",
        "equipment": "EQ-2367",
        "technician": "Michael Botha",
        "email": "michael.botha@metrocare.co.za",
        "score": 89,
    },
    {
        "reference": "MC-2026-1053",
        "equipment": "EQ-3478",
        "technician": "Priya Naidoo",
        "email": "priya.naidoo@metrocare.co.za",
        "score": 76,
    },
    {
        "reference": "MC-2026-1054",
        "equipment": "EQ-4590",
        "technician": "David Williams",
        "email": "david.williams@metrocare.co.za",
        "score": 91,
    },
    # Invalid: incorrect equipment code
    {
        "reference": "MC-2026-1055",
        "equipment": "EQUIP-1234",
        "technician": "Nomsa Mthembu",
        "email": "nomsa.mthembu@metrocare.co.za",
        "score": 68,
    },
    {
        "reference": "MC-2026-1056",
        "equipment": "EQ-5842",
        "technician": "Ryan Jacobs",
        "email": "ryan.jacobs@metrocare.co.za",
        "score": 94,
    },
    {
        "reference": "MC-2026-1057",
        "equipment": "EQ-6953",
        "technician": "Fatima Khan",
        "email": "fatima.khan@metrocare.co.za",
        "score": 82,
    },
    {
        "reference": "MC-2026-1058",
        "equipment": "EQ-7064",
        "technician": "Andile Ndlovu",
        "email": "andile.ndlovu@metrocare.co.za",
        "score": 88,
    },
    {
        "reference": "MC-2026-1059",
        "equipment": "EQ-8175",
        "technician": "Chloe Meyer",
        "email": "chloe.meyer@metrocare.co.za",
        "score": 79,
    },
    # Invalid: incorrect email
    {
        "reference": "MC-2026-1060",
        "equipment": "EQ-9286",
        "technician": "Peter Smith",
        "email": "peter.smith@metrocare",
        "score": 85,
    },
    {
        "reference": "MC-2026-1061",
        "equipment": "EQ-1397",
        "technician": "Busisiwe Zulu",
        "email": "busisiwe.zulu@metrocare.co.za",
        "score": 93,
    },
    {
        "reference": "MC-2026-1062",
        "equipment": "EQ-2408",
        "technician": "Kabelo Molefe",
        "email": "kabelo.molefe@metrocare.co.za",
        "score": 74,
    },
    {
        "reference": "MC-2026-1063",
        "equipment": "EQ-3519",
        "technician": "Samantha Ross",
        "email": "samantha.ross@metrocare.co.za",
        "score": 90,
    },
    {
        "reference": "MC-2026-1064",
        "equipment": "EQ-4630",
        "technician": "Mandla Sithole",
        "email": "mandla.sithole@metrocare.co.za",
        "score": 83,
    },
    # Invalid: incorrect reference
    {
        "reference": "MC-26-1065",
        "equipment": "EQ-5741",
        "technician": "Karen Adams",
        "email": "karen.adams@metrocare.co.za",
        "score": 77,
    },
    {
        "reference": "MC-2026-1066",
        "equipment": "EQ-6852",
        "technician": "Lunga Cele",
        "email": "lunga.cele@metrocare.co.za",
        "score": 96,
    },
    {
        "reference": "MC-2026-1067",
        "equipment": "EQ-7963",
        "technician": "Jessica Daniels",
        "email": "jessica.daniels@metrocare.co.za",
        "score": 86,
    },
    {
        "reference": "MC-2026-1068",
        "equipment": "EQ-8074",
        "technician": "Themba Mokoena",
        "email": "themba.mokoena@metrocare.co.za",
        "score": 80,
    },
    # Invalid: incorrect equipment code
    {
        "reference": "MC-2026-1069",
        "equipment": "EQ-12345",
        "technician": "Wendy Johnson",
        "email": "wendy.johnson@metrocare.co.za",
        "score": 72,
    },
]
